BGCOLOR = "#0F172A"
BGCOLOR_2 = "#16213B"

MAINCOLOR = "#F59E0B"
MAINCOLOR_DARK = "#B3750A"

TEXT_COLOR = "#E2E8F0"

DETAILS_COLOR = "#94A3B8"

ALTERNATIVE_COLOR_1 = "#10B981"
ALTERNATIVE_COLOR_2 = "#38BDF8"

TITILE_SIZE = 32
SUBTITLE_SIZE = 18
SUBSUBTITLE_SIZE = 16
BODY = 16


GAME_NAME = "topological racing"

TORUS_PRIVATE_NAME = "torus"
TORUS_PUBLIC_NAME = "torus"
KLEIN_PRIVATE_NAME = "klein"
KLEIN_PUBLIC_NAME = "klein bottle"
RP2_PRIVATE_NAME = "projectve"
RP2_PUBLIC_NAME = "projective plane"

SPACES = [TORUS_PRIVATE_NAME, KLEIN_PRIVATE_NAME, RP2_PRIVATE_NAME]

MAP1_PRIVATE_NAME = "pseudo"
MAP1_PUBLIC_NAME = "pseudo-circle"
MAP2_PRIVATE_NAME = "A"
MAP2_PUBLIC_NAME = "B"

MAPS = [MAP1_PRIVATE_NAME, MAP2_PRIVATE_NAME]

PLAYER_NAME_LEN = 15

IMG_SIZE = (64, 64)