DIMX = 750
DIMY = 750

BGCOLOR = "#0F172A"
BGCOLOR_2 = "#16213B"

MAINCOLOR = "#F59E0B"
MAINCOLOR_DARK = "#593205"

TEXT_COLOR = "#E2E8F0"

DETAILS_COLOR = "#94A3B8"

ALTERNATIVE_COLOR_1 = "#10B981"
ALTERNATIVE_COLOR_2 = "#38BDF8"

TITLE_SIZE = 32
SUBTITLE_SIZE = 18
SUBSUBTITLE_SIZE = 16
BODY = 16


GAME_NAME = "Topological Racing"

TORUS_PRIVATE_NAME = "torus"
TORUS_PUBLIC_NAME = "torus"
KLEIN_PRIVATE_NAME = "klein"
KLEIN_PUBLIC_NAME = "Klein Bottle"
RP2_PRIVATE_NAME = "projective"
RP2_PUBLIC_NAME = "Projective Plane"

SPACES = [TORUS_PRIVATE_NAME, KLEIN_PRIVATE_NAME, RP2_PRIVATE_NAME]

MAP1_PRIVATE_NAME = "pseudo"
MAP1_PUBLIC_NAME = "Pseudo-Circle"
MAP2_PRIVATE_NAME = "Z"
MAP2_PUBLIC_NAME = "Z-Homology"

MAPS = [MAP1_PRIVATE_NAME, MAP2_PRIVATE_NAME]

PLAYER_NAME_LEN = 15

IMG_SIZE = (64, 64)